### ISSUE TITLE
Toekn过期问题

### ISSUE THREAD

**Issue by ruabbit233** [java30kcoding/check_in#1]
这个token用在线的jwt解密发现过期时间是七天，请问怎么处理这个token刷新问题呢？

**Comment by java30kcoding** [comment]
我也没想好该怎么处理，考虑过期前邮件提醒，正常登陆获取token，然后提供一个接口去更新指定人的token

**Comment by ruabbit233** [comment]
确实也是没办法的事情呢 Orz

**Comment by java30kcoding** [comment]
新做了一版，可以实现扫码自动更新token或新增打卡人员，减少了每次更新token的复杂度
